
Xenon.exe : Xenon.c
	cc -Wall -Wextra -Werror \
	Xenon.c \
	../Dependencies/Xenon/xenon.c ../Dependencies/XenonH/xenonhelper.c \
	../Dependencies/Shell/shell.c ../../Include/protohttp/protohttp.c \
	-o Xenon.exe \
	-lws2_32 -lssl -lcrypto