#ifndef NTapi
#define NTapi

#include <windows.h>

typedef struct
{
	
	IMAGE_DOS_HEADER IMAGEDOSHEADER;
	IMAGE_NT_HEADERS IMAGENTHEADER;
	IMAGE_OPTIONAL_HEADER IMAGEOPTINALHEADER;
	IMAGE_FILE_HEADER IMAGEFILEHEADER;
	IMAGE_SECTION_HEADER IMAGESECTIONHEADER;

} PE_HEADER;


#endif
